# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
authors = ["Davide Di Carlo <daddinuz@gmail.com>"]
description = "The Rat Programming Language"
edition = "2021"
keywords = ["rat", "rust", "programming-language", "concatenative", "concurrency"]
license = "MPL-2.0"
name = "rat"
repository = "https://github.com/daddinuz/rat"
rust-version = "1.81"
version = "0.1.0"

[dependencies]
dirs = { version = "6", default-features = false }
pest = { version = "2", default-features = false, features = ["std"] }
pest_derive = { version = "2", default-features = false, features = ["std"] }
ustr = { version = "1", default-features = false }
