/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

Program = _{
    SOI ~ (Statement | Expression)* ~ EOI
}

Statement = {
    (DefineStatement | ImportStatement)
}

DefineStatement = {
    ":define" ~ Export? ~ Component ~ "="? ~ Expression+ ~ ";"
}

ImportStatement = {
    ":import" ~ Export? ~ Component ~ Identifier ~ ";"
}

Export = @{
    "^"
}

Component = @{
    ASCII_ALPHA ~ ASCII_ALPHANUMERIC* ~ ("-" ~ ASCII_ALPHA ~ ASCII_ALPHANUMERIC*)* ~ "!"? ~ "?"?
}

Identifier = @{
    Component ~ ("/" ~ Component)*
}

Expression = {
    (Boolean | Character | Decimal | Integer | Quote | String | Symbol | Identifier)
}

Boolean = @{
    ("⊥" | "⊤")
}

Character = ${
    "'" ~ UnicodeScalarValue ~ "'"
}

Decimal = @{
    ("+" | "-")? ~ ("∞" | "%" | (((ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*) | "0") ~ ((^"e" ~ ("+" | "-") ~ ASCII_DIGIT+) | "." ~ ASCII_DIGIT* ~ (^"e" ~ ("+" | "-") ~ ASCII_DIGIT+) | "." ~ ASCII_DIGIT+)))
}

Integer = @{
    ("+" | "-")? ~ ((ASCII_NONZERO_DIGIT ~ ASCII_DIGIT*) | "0")
}

Quote = {
    "[" ~ Expression* ~ "]"
}

String = ${
    "\"" ~ UnicodeScalarValue* ~ "\""
}

UnicodeScalarValue = @{
    (!("\"" | "\\" | NEWLINE) ~ ANY | "\\" ~ ("\"" | "'" | "\\" | "n" | "r" | "t" | ("u{" ~ ASCII_HEX_DIGIT{1, 4} ~ "}")))
}

Symbol = ${
    "$" ~ (Component | String)
}

WHITESPACE = _{ NEWLINE | "\t" | " " }
COMMENT    = _{ "#" ~ (!NEWLINE ~ ANY)* }
