[package]
name = "rat"
version = "0.1.3"
edition = "2024"
rust-version = "1.88"

[dependencies]
hashbrown = { version = "0.16", default-features = false, features = ["default-hasher", "inline-more"] }
pest = { version = "2.8", default-features = false, features = ["std"] }
pest_derive = { version = "2.8", default-features = false, features = ["std"] }
